name = "E3Runner"
uuid = "e3000000-0000-0000-0000-000000000001"
authors = ["East Contributors"]
version = "0.1.0"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[compat]
julia = "1.10"
